### ISSUE TITLE
devmemo

### ISSUE THREAD

**Issue by sorafujitani** [soramar/scrap_repository#1]

**Comment by sorafujitani** [comment]
リファクタリング前後でコードの品質を保証する
↓
テストコードを書く

捨てやすいコードを書く
 - 交換容易性
 - 依存度の低さ
 - class分割（単一責任）

**Comment by sorafujitani** [comment]
ロジックを抽象化して、外部から値を注入（di）

**Comment by sorafujitani** [comment]
class
- 交換可能な粒度

method
- 単一の仕事をする

数式に変換して考える（抽象化）
これだと構造化プログラミングなので、oop的な単純化見つける
手続きの抽象化
手続きと構造
- 〜の文字列が入力された場合
- 〜の条件の場合
抽象に依存する

 本質と仕様
本質と使用の分離をしないと、手続き的なプログラミングになる
使用　人の都合で変更になる可能性がある
本質　値に依存しない処理法則　
プリミティブのレベルで話す

di
クラスが依存する外部クラスのインスタンスを、内部でインスタンス化するのではなく外部から渡して
初期化するクラス設計。
オブジェクトが使う機能の実態を得る際、その解決を自力で行わず、常に外部から与えるようにするべき

ダックタイピングで抽象から具象に対してメソッドの詳細実装を強制する。
実行する具象クラスはどう判別するか。
↓
抽象クラスの実行側でdiする

条件や要件が増えた時に、抽象クラスに変更の必要がない設計

**Comment by soramar** [comment]
数式に変換して考える（抽象化）
これだと構造化プログラミングなので、oop的な単純化見つける
